version: '3.4'

services:
  memorymapperfrontend:
    image: memorymapperfrontend
    build:
      context: .
      dockerfile: ./Dockerfile
      no_cache: true
    expose:
      - 3000:3000
    depends_on:
      - memorymaptoolkit
      - db
    environment:
      - NEXT_PUBLIC_MAPTILER_KEY=${NEXT_PUBLIC_MAPTILER_KEY}
      - NEXT_PUBLIC_MEMORYMAPPER_ENDPOINT=${NEXT_PUBLIC_MEMORYMAPPER_ENDPOINT}
      - MEDIA_ROOT=${MEDIA_ROOT}
      - MEMORYMAPPER_ENDPOINT=${MEMORYMAPPER_ENDPOINT}
      - NEXT_PUBLIC_MEDIA_ROOT=${NEXT_PUBLIC_MEDIA_ROOT}
  db:
    image: kartoza/postgis:16-3.4
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${DJANGO_DB_USER}
      - POSTGRES_DBNAME=${DJANGO_DB_NAME}
      - POSTGRES_PASS=${DJANGO_DB_PASSWORD}
    expose:
      - 5432:5432
  memorymaptoolkit:
    image: ddunc23/memorymaptoolkit
    volumes:
      - static:/app/static
      - media:/app/media
    expose:
      - 8000:8000
    environment:
      - POSTGRES_USER=${DJANGO_DB_USER}
      - POSTGRES_NAME=${DJANGO_DB_NAME}
      - POSTGRES_PASSWORD=${DJANGO_DB_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_SECURE_SSL_HOST=${DJANGO_SECURE_SSL_HOST}
      - DJANGO_SESSION_COOKIE_SECURE=${DJANGO_SESSION_COOKIE_SECURE}
      - DJANGO_CSRF_COOKIE_SECURE=${DJANGO_CSRF_COOKIE_SECURE}
      - DJANGO_DB_HOST=${DJANGO_DB_HOST}
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - memorymaptoolkit
      - db
    volumes:
      - static:/usr/share/nginx/html/static
      - media:/usr/share/nginx/html/media
volumes:
  postgres_data:
  static:
  media:
